import Foundation
import Combine

// MARK: - ENVI Brain

/// The ENVI Brain — an autoresearch-inspired AI engine for content optimization.
///
/// ## The Autoresearch Pattern
///
/// Inspired by [karpathy/autoresearch](https://github.com/karpathy/autoresearch):
/// an autonomous improvement loop where an AI agent experiments, measures,
/// and iterates on a codebase to optimize a single metric (val_bpb).
///
/// From the autoresearch README:
/// > The idea: give an AI agent a small but real LLM training setup and let it
/// > experiment autonomously overnight. It modifies the code, trains for 5 minutes,
/// > checks if the result improved, keeps or discards, and repeats. You wake up in
/// > the morning to a log of experiments and (hopefully) a better model.
///
/// ## ENVI's Adaptation
///
/// Instead of optimizing val_bpb on a training script, the ENVI Brain optimizes
/// content engagement through an autonomous improvement loop:
///
/// ```
/// 1. OBSERVE   — Analyze the user's content library, engagement metrics, posting patterns
/// 2. HYPOTHESIZE — Generate predictions ("Post a carousel Wednesday 2pm → +23% engagement")
/// 3. EXECUTE   — The user posts (or accepts AI recommendation)
/// 4. MEASURE   — Track actual engagement vs. prediction
/// 5. LEARN     — Keep accurate prediction models, discard inaccurate ones
/// 6. ITERATE   — Continuously improve, getting smarter about this specific user
/// ```
///
/// ## Architecture (this file = program.md)
///
/// In autoresearch, the human writes `program.md` to orchestrate the agent.
/// This file IS the ENVI equivalent of `program.md` — it orchestrates all
/// AI subsystems:
///
/// - **ContentAnalyzer** → reads the "codebase" (content library + metrics)
/// - **PredictionEngine** → proposes "changes" (content recommendations)
/// - **ExperimentTracker** → logs results in "results.tsv" (experiment log)
/// - **TrendForecaster** → scans for new directions (trend opportunities)
/// - **InsightGenerator** → communicates findings to the "human" (user)
/// - **ResearchLoop** → the core experiment loop that ties it all together
///
/// From autoresearch:
/// > You are a completely autonomous researcher trying things out.
/// > If they work, keep. If they don't, discard. And you're advancing
/// > so that you can iterate.
///
/// The ENVI Brain embodies this philosophy for content creators.
final class ENVIBrain: ObservableObject {

    // MARK: - Singleton

    /// Shared instance — the single ENVI Brain for the app.
    ///
    /// Like autoresearch running on a single GPU with a single branch,
    /// there's one Brain per user, accumulating knowledge over time.
    static let shared = ENVIBrain()

    // MARK: - Published State

    /// Whether the Brain is currently processing (running a loop iteration).
    @Published var isProcessing: Bool = false

    /// Latest insights generated by the InsightGenerator.
    @Published var latestInsights: [InsightGenerator.ContentInsight] = []

    /// Current predictions from the PredictionEngine.
    @Published var predictions: [PredictionEngine.Prediction] = []

    /// The experiment log — all hypotheses tested, with keep/discard status.
    @Published var experimentLog: [ExperimentTracker.Experiment] = []

    /// Current state of the research loop.
    @Published var loopState: ResearchLoop.LoopState = .idle

    /// Total loop iterations completed since app install.
    @Published var totalIterations: Int = 0

    /// Overall keep rate — what fraction of the Brain's predictions were correct.
    @Published var overallKeepRate: Double = 0

    // MARK: - Subsystems

    /// Analyzes the user's content library for patterns.
    /// autoresearch equivalent: reading the current state of train.py.
    let contentAnalyzer: ContentAnalyzer

    /// Generates content predictions and recommendations.
    /// autoresearch equivalent: the agent proposing changes to train.py.
    let predictionEngine: PredictionEngine

    /// Forecasts trends and identifies upcoming opportunities.
    /// autoresearch equivalent: the agent reading papers for new ideas.
    let trendForecaster: TrendForecaster

    /// Generates natural-language insights for the user.
    /// autoresearch equivalent: commit messages and log output.
    let insightGenerator: InsightGenerator

    /// Tracks experiments and their keep/discard results.
    /// autoresearch equivalent: results.tsv.
    let experimentTracker: ExperimentTracker

    /// The core autoresearch loop adapted for content optimization.
    /// autoresearch equivalent: the LOOP FOREVER in program.md.
    let researchLoop: ResearchLoop

    private var cancellables = Set<AnyCancellable>()

    // MARK: - Initialization

    private init() {
        // Initialize all subsystems
        let analyzer = ContentAnalyzer()
        let engine = PredictionEngine()
        let forecaster = TrendForecaster()
        let generator = InsightGenerator()
        let tracker = ExperimentTracker()

        self.contentAnalyzer = analyzer
        self.predictionEngine = engine
        self.trendForecaster = forecaster
        self.insightGenerator = generator
        self.experimentTracker = tracker

        // Initialize the research loop with all dependencies
        self.researchLoop = ResearchLoop(
            contentAnalyzer: analyzer,
            predictionEngine: engine,
            experimentTracker: tracker,
            insightGenerator: generator,
            trendForecaster: forecaster
        )

        // Bind subsystem state to published properties
        setupBindings()
    }

    // MARK: - Bindings

    private func setupBindings() {
        // Forward research loop state
        researchLoop.$state
            .assign(to: &$loopState)

        researchLoop.$loopCount
            .assign(to: &$totalIterations)

        researchLoop.$keepRate
            .assign(to: &$overallKeepRate)

        researchLoop.$isRunning
            .assign(to: &$isProcessing)

        // Forward predictions
        predictionEngine.$predictions
            .assign(to: &$predictions)

        // Forward insights
        insightGenerator.$latestInsights
            .assign(to: &$latestInsights)

        // Forward experiment log
        experimentTracker.$experiments
            .assign(to: &$experimentLog)
    }

    // MARK: - Core Loop Methods

    /// Start the autonomous research loop.
    ///
    /// From autoresearch's program.md:
    /// > "Once you get confirmation, kick off the experimentation."
    ///
    /// Call this on app launch to begin the continuous improvement cycle.
    /// The loop runs on a schedule, triggering iterations on app events,
    /// content updates, and periodic background refresh.
    func startResearchLoop() {
        researchLoop.startLoop()
    }

    /// Pause the research loop.
    func pauseResearchLoop() {
        researchLoop.pauseLoop()
    }

    /// Observe the current content library and update internal models.
    ///
    /// autoresearch step 1: "Look at the git state."
    ///
    /// - Parameter contentLibrary: The user's content pieces
    func observe(contentLibrary: [ContentPiece]) {
        isProcessing = true
        defer { isProcessing = false }

        let patterns = contentAnalyzer.analyzeLibrary(contentLibrary)
        let _ = contentAnalyzer.identifyContentGaps(contentLibrary)
        let _ = contentAnalyzer.calculateEngagementTrend(over: ENVIBrainConfig.evaluationWindowDays)
        let _ = insightGenerator.generateWeeklyInsights(from: patterns)
    }

    /// Generate predictions based on current state.
    ///
    /// autoresearch step 2: "Tune train.py with an experimental idea."
    ///
    /// - Returns: Array of predictions sorted by priority and confidence
    func generatePredictions() -> [PredictionEngine.Prediction] {
        let predictions = predictionEngine.generatePredictions(
            for: ContentPiece.sampleLibrary,
            history: experimentTracker.experiments
        )
        return predictions
    }

    /// Evaluate an experiment after engagement data is available.
    ///
    /// autoresearch steps 5–9: Read results → keep or discard.
    ///
    /// - Parameter experiment: The experiment to evaluate
    /// - Returns: The result — keep, discard, or crash
    func evaluateExperiment(_ experiment: ExperimentTracker.Experiment) -> ExperimentResult {
        guard let resultValue = experiment.resultValue else {
            return ExperimentResult(
                experiment: experiment,
                decision: .pending,
                improvement: 0,
                explanation: "Waiting for engagement data. Results typically take \(ENVIBrainConfig.evaluationWindowDays) days."
            )
        }

        let improvement = experiment.baselineValue > 0
            ? (resultValue - experiment.baselineValue) / experiment.baselineValue
            : 0

        let decision: ExperimentDecision
        let explanation: String

        if improvement >= ENVIBrainConfig.keepThreshold {
            decision = .keep
            explanation = "Strategy improved engagement by \(String(format: "+%.1f", improvement * 100))%. Keeping this approach and incorporating into future recommendations."
        } else if improvement <= ENVIBrainConfig.discardThreshold {
            decision = .discard
            explanation = "Strategy decreased engagement by \(String(format: "%.1f", improvement * 100))%. Discarding and reverting to previous approach."
        } else {
            decision = .discard
            explanation = "No significant change (\(String(format: "%+.1f", improvement * 100))%). Discarding — marginal changes aren't worth the complexity."
        }

        return ExperimentResult(
            experiment: experiment,
            decision: decision,
            improvement: improvement,
            explanation: explanation
        )
    }

    // MARK: - Chat Integration

    /// Get insights relevant to a chat query.
    ///
    /// Powers the ENVI chat's AI responses. The user asks a question,
    /// and the Brain provides data-backed insights.
    ///
    /// Maps to the World Explorer's suggestion chips:
    /// - "What does my content say about me?"
    /// - "Optimize my latest post"
    /// - "What should I publish next?"
    /// - "Repurpose my top content"
    /// - "Analyze engagement trends"
    func getInsightsForChat(query: String) -> [InsightGenerator.ContentInsight] {
        guard let patterns = contentAnalyzer.currentPattern else {
            // Run observation first if no patterns exist
            observe(contentLibrary: ContentPiece.sampleLibrary)
            guard let patterns = contentAnalyzer.currentPattern else { return [] }
            let response = insightGenerator.generateChatResponse(for: query, context: patterns)
            return response.insights
        }

        let response = insightGenerator.generateChatResponse(for: query, context: patterns)
        return response.insights
    }

    /// Get a full chat response including suggested follow-up questions.
    func getChatResponse(query: String) -> InsightGenerator.ChatInsightResponse {
        let patterns = contentAnalyzer.currentPattern ?? contentAnalyzer.analyzeLibrary(ContentPiece.sampleLibrary)
        return insightGenerator.generateChatResponse(for: query, context: patterns)
    }

    // MARK: - Future Predictions

    /// Get predictions for future content, starting from a given date.
    ///
    /// These power the "future" section of the timeline — ghost/dashed
    /// content pieces with AI recommendations extending beyond the present.
    ///
    /// - Parameters:
    ///   - date: Start date for predictions
    ///   - count: Number of predictions to generate
    /// - Returns: Predictions sorted by date
    func getFuturePredictions(from date: Date, count: Int) -> [PredictionEngine.Prediction] {
        let allPredictions = predictionEngine.predictions.isEmpty
            ? generatePredictions()
            : predictionEngine.predictions

        return Array(
            allPredictions
                .filter { $0.suggestedDate >= date }
                .sorted { $0.suggestedDate < $1.suggestedDate }
                .prefix(count)
        )
    }

    // MARK: - Event Handlers

    /// Notify the Brain that new content was added.
    func contentAdded(_ piece: ContentPiece) {
        researchLoop.onContentAdded(piece)
    }

    /// Notify the Brain that metrics were updated.
    func metricsUpdated(for pieceId: String, metrics: ContentMetrics) {
        researchLoop.onMetricsUpdated(for: pieceId, metrics: metrics)
    }

    /// Notify the Brain that the app launched.
    func appLaunched() {
        researchLoop.onAppLaunch()
    }

    // MARK: - Status

    /// Get the current status of the ENVI Brain.
    var status: BrainStatus {
        let loopStatus = researchLoop.getStatus()
        let experimentSummary = experimentTracker.summary

        return BrainStatus(
            isProcessing: isProcessing,
            loopState: loopState,
            totalIterations: totalIterations,
            keepRate: overallKeepRate,
            activeExperiments: experimentSummary.active,
            totalExperiments: experimentSummary.total,
            insightCount: latestInsights.count,
            predictionCount: predictions.count,
            lastIteration: loopStatus.lastIterationDate,
            contentGaps: contentAnalyzer.contentGaps.count,
            trendDirection: contentAnalyzer.trendDirection
        )
    }
}

// MARK: - Supporting Types

/// The result of evaluating an experiment.
struct ExperimentResult {
    let experiment: ExperimentTracker.Experiment
    let decision: ExperimentDecision
    let improvement: Double             // Fraction: +0.05 = 5% improvement
    let explanation: String
}

/// The keep/discard/pending decision for an experiment.
enum ExperimentDecision: String {
    case keep       // Improved the metric → incorporate into future recommendations
    case discard    // Didn't improve → revert to previous approach
    case pending    // Not enough data yet
}

/// Comprehensive status of the ENVI Brain.
struct BrainStatus {
    let isProcessing: Bool
    let loopState: ResearchLoop.LoopState
    let totalIterations: Int
    let keepRate: Double
    let activeExperiments: Int
    let totalExperiments: Int
    let insightCount: Int
    let predictionCount: Int
    let lastIteration: Date?
    let contentGaps: Int
    let trendDirection: ContentAnalyzer.TrendDirection

    /// Human-readable summary of the Brain's status.
    var summary: String {
        let stateStr: String
        switch loopState {
        case .idle:          stateStr = "Idle"
        case .observing:     stateStr = "Analyzing your content..."
        case .hypothesizing: stateStr = "Generating predictions..."
        case .waiting:       stateStr = "Monitoring experiments..."
        case .evaluating:    stateStr = "Evaluating results..."
        case .learning:      stateStr = "Updating models..."
        }

        let keepRateStr = totalExperiments > 0
            ? "\(Int(keepRate * 100))% prediction accuracy"
            : "No experiments yet"

        return "\(stateStr) | \(totalIterations) iterations | \(keepRateStr)"
    }
}
