import Foundation

// MARK: - Insight Category

/// Categories of insights the ENVI Brain can generate.
/// Determines visual treatment and priority in the UI.
/// Mirrors InsightGenerator.InsightCategory for the top-level model layer.
enum InsightCategory: String, CaseIterable, Codable {
    case performance      // How content is performing
    case recommendation   // What to do next
    case trend            // What's trending
    case alert            // Something needs attention
    case milestone        // Achievement or milestone reached
}

// MARK: - Insight Data Point

/// A supporting data point for a ContentInsight.
/// Displayed as metric cards or inline stats within an insight.
struct InsightDataPoint: Identifiable, Codable {
    let id: UUID
    let label: String
    let value: String
    let change: String
    let trend: MetricTrend

    init(
        id: UUID = UUID(),
        label: String,
        value: String,
        change: String = "",
        trend: MetricTrend = .neutral
    ) {
        self.id = id
        self.label = label
        self.value = value
        self.change = change
        self.trend = trend
    }
}

// MARK: - Content Insight

/// An insight generated by the ENVI Brain for display in chat and UI.
///
/// Insights are the human-readable output of the Brain's analysis —
/// translating raw patterns and predictions into actionable recommendations.
/// Generated by ENVIBrain.shared via its InsightGenerator subsystem.
struct ContentInsight: Identifiable, Codable {
    let id: UUID
    let title: String
    let body: String
    let category: InsightCategory
    let actionable: Bool
    let actionLabel: String?
    let confidence: Double
    let dataPoints: [InsightDataPoint]

    init(
        id: UUID = UUID(),
        title: String,
        body: String,
        category: InsightCategory,
        actionable: Bool,
        actionLabel: String? = nil,
        confidence: Double,
        dataPoints: [InsightDataPoint] = []
    ) {
        self.id = id
        self.title = title
        self.body = body
        self.category = category
        self.actionable = actionable
        self.actionLabel = actionLabel
        self.confidence = min(max(confidence, 0.0), 1.0)
        self.dataPoints = dataPoints
    }
}

// MARK: - Sample Insights

extension ContentInsight {

    /// Sample insights for previews and initial state.
    /// In production, generated by ENVIBrain.shared.getInsightsForChat(query:).
    static let sampleInsights: [ContentInsight] = [
        ContentInsight(
            title: "Weekly Performance Overview",
            body: "You published 14 pieces this period. Your best-performing format is video on Instagram, with an average engagement rate of 4.8%.",
            category: .performance,
            actionable: false,
            confidence: 0.95,
            dataPoints: [
                InsightDataPoint(label: "Total Content", value: "14 pieces", trend: .neutral),
                InsightDataPoint(label: "Best Format", value: "Video", change: "+23%", trend: .up),
                InsightDataPoint(label: "Avg Engagement", value: "4.8%", change: "+0.6%", trend: .up),
            ]
        ),
        ContentInsight(
            title: "Peak Engagement Window",
            body: "Wednesday at 2pm is your golden hour. Posts during this window see 34% higher engagement than your average.",
            category: .recommendation,
            actionable: true,
            actionLabel: "Schedule for Wednesday 2pm",
            confidence: 0.88,
            dataPoints: [
                InsightDataPoint(label: "Peak Day", value: "Wednesday", trend: .neutral),
                InsightDataPoint(label: "Peak Hour", value: "2:00 PM", trend: .neutral),
                InsightDataPoint(label: "Eng. Rate", value: "6.4%", change: "+34%", trend: .up),
            ]
        ),
        ContentInsight(
            title: "Content Gap Detected",
            body: "You haven't posted a carousel in 12 days. Carousels drive 2.3x more saves than photos — consider creating one this week.",
            category: .alert,
            actionable: true,
            actionLabel: "Create a carousel",
            confidence: 0.82,
            dataPoints: [
                InsightDataPoint(label: "Days Since", value: "12 days", change: "overdue", trend: .down),
                InsightDataPoint(label: "Save Rate", value: "2.3x", change: "vs. photos", trend: .up),
            ]
        ),
        ContentInsight(
            title: "Engagement Trend: Improving",
            body: "Your engagement rate has increased 18% over the past two weeks. Video content and consistent posting frequency are the primary drivers.",
            category: .trend,
            actionable: false,
            confidence: 0.90,
            dataPoints: [
                InsightDataPoint(label: "Trend", value: "Improving", change: "+18%", trend: .up),
                InsightDataPoint(label: "Driver", value: "Video", trend: .neutral),
                InsightDataPoint(label: "Growth Rate", value: "+12/day", change: "steady", trend: .up),
            ]
        ),
        ContentInsight(
            title: "Milestone: 10K Total Engagement",
            body: "Your content crossed 10,000 total engagements this week. Reel content on Instagram was the biggest contributor at 42% of total interactions.",
            category: .milestone,
            actionable: false,
            confidence: 0.99,
            dataPoints: [
                InsightDataPoint(label: "Total", value: "10,234", change: "milestone!", trend: .up),
                InsightDataPoint(label: "Top Format", value: "Reels", change: "42%", trend: .up),
            ]
        ),
    ]
}
