import Foundation

// MARK: - Prediction Category

/// Categories of predictions the ENVI Brain can generate.
/// Maps to PredictionEngine.PredictionType for the future timeline.
enum PredictionCategory: String, CaseIterable, Codable {
    case contentRecommendation   // What format/topic to create
    case optimalPostTime         // Best time window
    case trendOpportunity        // Leverage a trending topic
    case contentGap              // Missing content type
    case importantDate           // Holiday or milestone
    case audiencePeak            // Audience activity window
}

// MARK: - Prediction Priority

/// Priority ranking for predictions, used to sort timeline items.
enum PredictionPriority: Int, Comparable, Codable {
    case critical = 4
    case high = 3
    case medium = 2
    case low = 1

    static func < (lhs: PredictionPriority, rhs: PredictionPriority) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

// MARK: - Predicted Engagement

/// Forecasted engagement metrics for a prediction.
/// Generated by ENVIBrain's PredictionEngine based on historical patterns.
struct PredictedEngagement: Codable {
    let views: Int
    let likes: Int
    let shares: Int
    let engagementRate: Double

    var summary: String {
        let viewsStr = views >= 1000 ? "\(String(format: "%.1f", Double(views) / 1000))K" : "\(views)"
        return "\(viewsStr) views, \(String(format: "%.1f", engagementRate * 100))% engagement"
    }
}

// MARK: - Content Prediction

/// A prediction generated by the ENVI Brain for future content.
/// These appear as ghost/recommended pieces on the future timeline.
///
/// The ENVI Brain (ENVIBrain.shared) produces these through its PredictionEngine,
/// which uses the autoresearch pattern: observe → hypothesize → measure → learn.
/// Each prediction is a hypothesis that the Brain will track and evaluate.
struct ContentPrediction: Identifiable, Codable {
    let id: UUID
    let title: String
    let description: String
    let suggestedType: ContentType
    let suggestedPlatform: ContentPlatform
    let suggestedDate: Date
    let confidence: Double              // 0.0–1.0
    let predictedEngagement: PredictedEngagement
    let reasoning: String               // "Based on your patterns..."
    let category: PredictionCategory
    let priority: PredictionPriority

    init(
        id: UUID = UUID(),
        title: String,
        description: String,
        suggestedType: ContentType,
        suggestedPlatform: ContentPlatform,
        suggestedDate: Date,
        confidence: Double,
        predictedEngagement: PredictedEngagement,
        reasoning: String,
        category: PredictionCategory,
        priority: PredictionPriority
    ) {
        self.id = id
        self.title = title
        self.description = description
        self.suggestedType = suggestedType
        self.suggestedPlatform = suggestedPlatform
        self.suggestedDate = suggestedDate
        self.confidence = min(max(confidence, 0.0), 1.0)
        self.predictedEngagement = predictedEngagement
        self.reasoning = reasoning
        self.category = category
        self.priority = priority
    }
}

// MARK: - Sample Predictions

extension ContentPrediction {

    /// Sample predictions matching the future timeline content from ContentPiece.futurePieces.
    /// In production, these are generated by ENVIBrain.shared.generatePredictions().
    static let samplePredictions: [ContentPrediction] = {
        let calendar = Calendar.current
        let now = Date()

        func date(daysFromNow days: Int) -> Date {
            calendar.date(byAdding: .day, value: days, to: now) ?? now
        }

        return [
            ContentPrediction(
                title: "Trend Video — Trending Audio Remix",
                description: "Create a trend remix video using the currently viral audio. Your audience engagement peaks with short-form trend content on TikTok.",
                suggestedType: .reel,
                suggestedPlatform: .tiktok,
                suggestedDate: date(daysFromNow: 2),
                confidence: 0.87,
                predictedEngagement: PredictedEngagement(views: 15000, likes: 1800, shares: 420, engagementRate: 0.148),
                reasoning: "Your last 3 TikTok trend remixes averaged 34K views. Current audio is trending upward with 12M uses this week. Posting within the next 48hrs maximizes reach.",
                category: .contentRecommendation,
                priority: .high
            ),
            ContentPrediction(
                title: "Carousel — Week Recap for LinkedIn",
                description: "Weekly recap carousel summarizing your top content moments. LinkedIn carousels from your account see 2.3x higher impressions than static posts.",
                suggestedType: .carousel,
                suggestedPlatform: .linkedin,
                suggestedDate: date(daysFromNow: 4),
                confidence: 0.82,
                predictedEngagement: PredictedEngagement(views: 3000, likes: 380, shares: 145, engagementRate: 0.175),
                reasoning: "Your LinkedIn audience is most active on Sundays. Weekly recap carousels in your niche see 40% higher save rates than standalone posts.",
                category: .optimalPostTime,
                priority: .medium
            ),
            ContentPrediction(
                title: "National Coffee Day — Brand Moment",
                description: "April 1 is National Coffee Day — a high-engagement brand moment. Lifestyle photo tying your brand to the cultural moment.",
                suggestedType: .photo,
                suggestedPlatform: .instagram,
                suggestedDate: date(daysFromNow: 6),
                confidence: 0.91,
                predictedEngagement: PredictedEngagement(views: 9500, likes: 1400, shares: 310, engagementRate: 0.18),
                reasoning: "National Coffee Day generated 2.1M Instagram posts last year. Brands in your category saw 3x engagement spikes. Early posting (7-9am) captures peak interest.",
                category: .importantDate,
                priority: .critical
            ),
            ContentPrediction(
                title: "Peak Engagement Window — Schedule Here",
                description: "AI detected your highest-engagement posting window. Schedule any content during this window for maximum reach.",
                suggestedType: .story,
                suggestedPlatform: .instagram,
                suggestedDate: date(daysFromNow: 8),
                confidence: 0.93,
                predictedEngagement: PredictedEngagement(views: 5200, likes: 780, shares: 120, engagementRate: 0.173),
                reasoning: "Analysis of your last 90 days shows Thursday 2-4pm is your highest engagement window. Followers online: +47% vs. average.",
                category: .audiencePeak,
                priority: .high
            ),
            ContentPrediction(
                title: "Content Gap — No Video in 14 Days",
                description: "You haven't published video content in 14 days. Your video posts drive 60% of total engagement — this gap may impact growth.",
                suggestedType: .video,
                suggestedPlatform: .tiktok,
                suggestedDate: date(daysFromNow: 10),
                confidence: 0.85,
                predictedEngagement: PredictedEngagement(views: 12000, likes: 1500, shares: 340, engagementRate: 0.153),
                reasoning: "Your video content averages 4.2x more engagement than photo posts. Going 14+ days without video historically correlates with a 20% follower engagement drop.",
                category: .contentGap,
                priority: .critical
            ),
            ContentPrediction(
                title: "Collaboration Cross-Post Opportunity",
                description: "Cross-posting with partners in your niche drives mutual audience growth and 2x engagement on carousel format.",
                suggestedType: .carousel,
                suggestedPlatform: .instagram,
                suggestedDate: date(daysFromNow: 12),
                confidence: 0.78,
                predictedEngagement: PredictedEngagement(views: 8000, likes: 1200, shares: 280, engagementRate: 0.185),
                reasoning: "Your last collab post (Mar 8) drove 11.2K views and 201 comments — your highest engagement that week. Partner accounts with 5K-50K followers see the best cross-pollination.",
                category: .trendOpportunity,
                priority: .medium
            ),
        ]
    }()
}
