import UIKit
import SwiftUI

/// 3-tab controller matching Sketch "Main App" design.
///
/// Tab 0: For You / Gallery (swipeable content + masonry grid)
/// Tab 1: World Explorer / AI Chat (ENVI logo center)
/// Tab 2: Profile + Settings (circle icon)
///
/// Condensed pill: 164pt wide, #4A60B2 fill, 3 icons.
final class MainTabBarController: UIViewController {

    var onSignOut: (() -> Void)?

    private let customTabBar = ENVITabBar()
    private var viewControllers: [UIViewController] = []
    private var currentIndex = 0
    private var trackedScrollViews: [UIScrollView] = []

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = ENVITheme.UIKit.backgroundDark
        setupViewControllers()
        setupTabBar()
        attachViewControllersIfNeeded()
        showViewController(at: 0)
    }

    // MARK: - Tab Setup

    private func setupViewControllers() {
        // Tab 0: For You / Gallery
        // "For You" shows swipeable template-generated content pieces from camera roll.
        // "Gallery" shows masonry grid with Social Media Arsenal of approved content.
        let forYouGalleryVC = makeForYouGalleryViewController()

        // Tab 1: World Explorer / AI Chat (center ENVI logo)
        let chatExploreVC = UIHostingController(rootView: ChatExploreView().requiresAura())
        chatExploreVC.view.backgroundColor = ENVITheme.UIKit.backgroundDark

        // Tab 2: Profile + Settings
        let profileView = ProfileView(onSignOut: { [weak self] in
            self?.onSignOut?()
        })
        let profileVC = UIHostingController(rootView: profileView)
        profileVC.view.backgroundColor = ENVITheme.UIKit.backgroundDark

        viewControllers = [forYouGalleryVC, chatExploreVC, profileVC]
    }

    /// Builds Tab 0 — the For You / Gallery dual-mode view.
    /// For You: swipeable content pieces generated by the template engine.
    /// Gallery: masonry grid of the user's approved content arsenal.
    @MainActor
    private func makeForYouGalleryViewController() -> UIViewController {
        let containerView = ForYouGalleryContainerView()
        let hostingVC = UIHostingController(rootView: containerView)
        hostingVC.view.backgroundColor = ENVITheme.UIKit.backgroundDark
        return hostingVC
    }

    // MARK: - Tab Bar

    private func setupTabBar() {
        customTabBar.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(customTabBar)

        NSLayoutConstraint.activate([
            customTabBar.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            customTabBar.widthAnchor.constraint(equalToConstant: 164),
            customTabBar.heightAnchor.constraint(equalToConstant: 64),
            customTabBar.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -6),
        ])

        customTabBar.onTabSelected = { [weak self] index in
            self?.showViewController(at: index)
        }
    }

    // MARK: - View Controller Switching

    private func showViewController(at index: Int) {
        guard index < viewControllers.count else { return }

        if currentIndex == index {
            let current = viewControllers[index]
            customTabBar.selectedIndex = index
            setTabBarVisible(true, animated: false)
            configureTabBarVisibilityHandling(for: current)
            return
        }

        attachViewControllersIfNeeded()

        if currentIndex < viewControllers.count {
            viewControllers[currentIndex].view.isHidden = true
        }

        let newVC = viewControllers[index]
        newVC.view.isHidden = false
        view.bringSubviewToFront(customTabBar)

        currentIndex = index
        customTabBar.selectedIndex = index
        setTabBarVisible(true, animated: false)
        configureTabBarVisibilityHandling(for: newVC)
    }

    private func attachViewControllersIfNeeded() {
        guard viewControllers.allSatisfy({ $0.parent === self }) == false else {
            for viewController in viewControllers {
                viewController.view.isHidden = true
            }
            return
        }

        for (index, viewController) in viewControllers.enumerated() {
            guard viewController.parent == nil else {
                viewController.view.isHidden = true
                continue
            }

            addChild(viewController)
            viewController.view.translatesAutoresizingMaskIntoConstraints = false
            viewController.view.isHidden = index != currentIndex
            view.insertSubview(viewController.view, belowSubview: customTabBar)

            NSLayoutConstraint.activate([
                viewController.view.topAnchor.constraint(equalTo: view.topAnchor),
                viewController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
                viewController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                viewController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            ])
            viewController.didMove(toParent: self)
        }
    }

    func setTabBarVisible(_ visible: Bool, animated: Bool = true) {
        customTabBar.setVisible(visible, animated: animated)
    }

    // MARK: - Scroll-Driven Tab Bar Hiding

    private func configureTabBarVisibilityHandling(for viewController: UIViewController) {
        clearTrackedScrollViews()

        let attachHandlers = { [weak self, weak viewController] in
            guard let self, let viewController else { return }
            let scrollViews = self.findScrollViews(in: viewController.view)
                .filter { $0.contentSize.height > $0.bounds.height + 40 }

            self.trackedScrollViews = scrollViews
            for scrollView in scrollViews {
                scrollView.panGestureRecognizer.removeTarget(self, action: #selector(self.handleTrackedScrollPan(_:)))
                scrollView.panGestureRecognizer.addTarget(self, action: #selector(self.handleTrackedScrollPan(_:)))
            }
        }

        DispatchQueue.main.async(execute: attachHandlers)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2, execute: attachHandlers)
    }

    private func clearTrackedScrollViews() {
        for scrollView in trackedScrollViews {
            scrollView.panGestureRecognizer.removeTarget(self, action: #selector(handleTrackedScrollPan(_:)))
        }
        trackedScrollViews.removeAll()
    }

    private func findScrollViews(in rootView: UIView) -> [UIScrollView] {
        var scrollViews: [UIScrollView] = []
        if let scrollView = rootView as? UIScrollView {
            scrollViews.append(scrollView)
        }
        for subview in rootView.subviews {
            scrollViews.append(contentsOf: findScrollViews(in: subview))
        }
        return scrollViews
    }

    @objc private func handleTrackedScrollPan(_ gestureRecognizer: UIPanGestureRecognizer) {
        guard
            gestureRecognizer.state == .changed,
            let scrollView = gestureRecognizer.view as? UIScrollView
        else { return }

        let translation = gestureRecognizer.translation(in: scrollView)
        guard abs(translation.y) > abs(translation.x) else { return }

        let topOffset = -scrollView.adjustedContentInset.top
        let nearTop = scrollView.contentOffset.y <= topOffset + 20

        if nearTop || translation.y > 6 {
            setTabBarVisible(true, animated: true)
        } else if translation.y < -6 {
            setTabBarVisible(false, animated: true)
        }
    }
}
