import UIKit
import SwiftUI
import Combine

/// 3-tab controller.
///
/// Tab 0: For You / Gallery (swipeable content + masonry grid)
/// Tab 1: World Explorer / AI Chat (ENVI logo center)
/// Tab 2: Profile + Settings (circle icon)
///
/// Pill: 164pt wide, #7A56C4 fill, 3 icons (Home / World Explorer / Profile — see ENVITabBar.pillWidth).
///
/// Publishing is not a tab. It surfaces as a top-right nav icon inside the
/// For You / Gallery header (`MainAppHeader`), which calls
/// `router.present(.publishing)` to sheet-present `PublishingTabView`.
///
/// Phase 15-02: owns a shared `AppRouter` instance that every tab root
/// receives via `.environmentObject(router)`. `router.selectedTab` is
/// two-way synced with `currentIndex`: programmatic
/// `router.selectTab(n)` switches tabs via the same path as a tab-bar
/// tap, and tab-bar taps write back to `router.selectedTab` so both
/// stay in lockstep.
final class MainTabBarController: UIViewController {

    var onSignOut: (() -> Void)?

    private let customTabBar = ENVITabBar()
    private var viewControllers: [UIViewController] = []
    private var currentIndex = 0
    private var trackedScrollViews: [UIScrollView] = []

    /// Tap recognizer used to *reveal* the tab bar while the center tab
    /// (index 1) is active. The world-explorer view auto-hides the pill so
    /// the 3D helix can breathe; tapping anywhere in the bottom ~80pt strip
    /// pops it back in. Location filtering happens in the action handler so
    /// other gestures on the scene stay untouched.
    private var bottomTapRevealGesture: UITapGestureRecognizer?

    /// Center tab (World Explorer / AI Chat) — code index 1. Kept as a
    /// named constant so the auto-hide intent is obvious at every use-site.
    private static let centerTabIndex = 1

    /// Shared router injected into each tab's SwiftUI root via
    /// `.environmentObject`.
    private let router = AppRouter.shared

    /// Combine subscription that observes `router.selectedTab` → tab
    /// switch. Discarded on deinit.
    private var routerTabCancellable: AnyCancellable?

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = ENVITheme.UIKit.backgroundDark
        setupViewControllers()
        setupTabBar()
        setupBottomTapRevealGesture()
        attachViewControllersIfNeeded()
        showViewController(at: 0)
        bindRouter()
    }

    // MARK: - Router sync

    /// Wire `router.selectedTab` → `showViewController` so programmatic
    /// router-driven navigation from SwiftUI lands on the right tab.
    private func bindRouter() {
        routerTabCancellable = router.$selectedTab
            .receive(on: DispatchQueue.main)
            .sink { [weak self] index in
                guard let self = self, index != self.currentIndex else { return }
                self.showViewController(at: index)
            }
    }

    // MARK: - Tab Setup

    private func setupViewControllers() {
        // Tab 0: For You / Gallery
        // "For You" shows swipeable template-generated content pieces from camera roll.
        // "Gallery" shows masonry grid with Social Media Arsenal of approved content.
        let forYouGalleryVC = makeForYouGalleryViewController()

        // Tab 1: World Explorer / AI Chat (center ENVI logo)
        let chatExploreVC = UIHostingController(
            rootView: ChatExploreView()
                .requiresAura()
                .environmentObject(router)
        )
        chatExploreVC.view.backgroundColor = ENVITheme.UIKit.backgroundDark

        // Tab 2: Profile + Settings
        let profileView = ProfileView(onSignOut: { [weak self] in
            self?.onSignOut?()
        })
        let profileVC = UIHostingController(
            rootView: profileView
                .environmentObject(router)
        )
        profileVC.view.backgroundColor = ENVITheme.UIKit.backgroundDark

        viewControllers = [forYouGalleryVC, chatExploreVC, profileVC]
    }

    /// Builds Tab 0 — the For You / Gallery dual-mode view.
    /// For You: swipeable content pieces generated by the template engine.
    /// Gallery: masonry grid of the user's approved content arsenal.
    @MainActor
    private func makeForYouGalleryViewController() -> UIViewController {
        let containerView = HomeFeedContainerView()
            .environmentObject(router)
        let hostingVC = UIHostingController(rootView: containerView)
        hostingVC.view.backgroundColor = ENVITheme.UIKit.backgroundDark
        return hostingVC
    }

    // MARK: - Tab Bar

    private func setupTabBar() {
        customTabBar.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(customTabBar)

        NSLayoutConstraint.activate([
            customTabBar.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            customTabBar.widthAnchor.constraint(equalToConstant: ENVITabBar.pillWidth),
            customTabBar.heightAnchor.constraint(equalToConstant: ENVITabBar.pillHeight),
            customTabBar.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -6),
        ])

        customTabBar.onTabSelected = { [weak self] index in
            self?.showViewController(at: index)
            // Mirror to router so SwiftUI observers (and future
            // `router.selectedTab` readers) stay in sync.
            self?.router.selectedTab = index
        }
    }

    // MARK: - Bottom-Tap Reveal Gesture

    /// Installs a `UITapGestureRecognizer` on the tab-bar controller's root
    /// view. When the center tab (World Explorer) is active and the pill is
    /// hidden, a tap in the bottom ~80pt strip of the screen reveals it.
    /// `cancelsTouchesInView = false` so taps still reach the underlying
    /// SceneKit / SwiftUI views (helix scene, bottom composer, suggestion
    /// chips, etc.) — the gesture fires in parallel and is filtered by
    /// y-location inside the action handler.
    private func setupBottomTapRevealGesture() {
        let gesture = UITapGestureRecognizer(
            target: self,
            action: #selector(handleBottomTapReveal(_:))
        )
        gesture.cancelsTouchesInView = false
        gesture.delaysTouchesBegan = false
        gesture.delaysTouchesEnded = false
        view.addGestureRecognizer(gesture)
        bottomTapRevealGesture = gesture
    }

    /// Height of the tap target at the bottom of the screen that reveals the
    /// hidden pill. Generous enough to catch a comfortable thumb tap but
    /// narrow enough that taps on the World Explorer bottom composer still
    /// take priority (composer sits above this strip once the pill is
    /// hidden).
    private static let bottomRevealTapZoneHeight: CGFloat = 80

    @objc private func handleBottomTapReveal(_ gesture: UITapGestureRecognizer) {
        // Only arm the reveal while the center tab is active — everywhere
        // else the pill is already visible.
        guard currentIndex == MainTabBarController.centerTabIndex else { return }
        guard gesture.state == .ended else { return }

        let location = gesture.location(in: view)
        let threshold = view.bounds.height - MainTabBarController.bottomRevealTapZoneHeight
        guard location.y >= threshold else { return }

        setTabBarVisible(true, animated: true)
    }

    // MARK: - View Controller Switching

    private func showViewController(at index: Int) {
        guard index < viewControllers.count else { return }

        if currentIndex == index {
            let current = viewControllers[index]
            customTabBar.selectedIndex = index
            applyTabBarVisibility(forTabIndex: index, animated: false)
            configureTabBarVisibilityHandling(for: current)
            return
        }

        attachViewControllersIfNeeded()

        if currentIndex < viewControllers.count {
            viewControllers[currentIndex].view.isHidden = true
        }

        let newVC = viewControllers[index]
        newVC.view.isHidden = false
        view.bringSubviewToFront(customTabBar)

        currentIndex = index
        customTabBar.selectedIndex = index
        applyTabBarVisibility(forTabIndex: index, animated: true)
        configureTabBarVisibilityHandling(for: newVC)
    }

    /// Central rule for whether the pill should be visible when a given tab
    /// becomes active. The center tab (World Explorer) auto-hides the pill so
    /// the 3D helix reads full-bleed; every other tab shows it by default.
    /// Scroll-driven visibility continues to override this on tabs where the
    /// content scroll view is long enough to warrant it.
    private func applyTabBarVisibility(forTabIndex index: Int, animated: Bool) {
        if index == MainTabBarController.centerTabIndex {
            setTabBarVisible(false, animated: animated)
        } else {
            setTabBarVisible(true, animated: animated)
        }
    }

    private func attachViewControllersIfNeeded() {
        guard viewControllers.allSatisfy({ $0.parent === self }) == false else {
            for viewController in viewControllers {
                viewController.view.isHidden = true
            }
            return
        }

        for (index, viewController) in viewControllers.enumerated() {
            guard viewController.parent == nil else {
                viewController.view.isHidden = true
                continue
            }

            addChild(viewController)
            viewController.view.translatesAutoresizingMaskIntoConstraints = false
            viewController.view.isHidden = index != currentIndex
            view.insertSubview(viewController.view, belowSubview: customTabBar)

            NSLayoutConstraint.activate([
                viewController.view.topAnchor.constraint(equalTo: view.topAnchor),
                viewController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
                viewController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                viewController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            ])
            viewController.didMove(toParent: self)
        }
    }

    func setTabBarVisible(_ visible: Bool, animated: Bool = true) {
        customTabBar.setVisible(visible, animated: animated)
    }

    // MARK: - Scroll-Driven Tab Bar Hiding

    private func configureTabBarVisibilityHandling(for viewController: UIViewController) {
        clearTrackedScrollViews()

        let attachHandlers = { [weak self, weak viewController] in
            guard let self, let viewController else { return }
            let scrollViews = self.findScrollViews(in: viewController.view)
                .filter { $0.contentSize.height > $0.bounds.height + 40 }

            self.trackedScrollViews = scrollViews
            for scrollView in scrollViews {
                scrollView.panGestureRecognizer.removeTarget(self, action: #selector(self.handleTrackedScrollPan(_:)))
                scrollView.panGestureRecognizer.addTarget(self, action: #selector(self.handleTrackedScrollPan(_:)))
            }
        }

        DispatchQueue.main.async(execute: attachHandlers)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2, execute: attachHandlers)
    }

    private func clearTrackedScrollViews() {
        for scrollView in trackedScrollViews {
            scrollView.panGestureRecognizer.removeTarget(self, action: #selector(handleTrackedScrollPan(_:)))
        }
        trackedScrollViews.removeAll()
    }

    private func findScrollViews(in rootView: UIView) -> [UIScrollView] {
        var scrollViews: [UIScrollView] = []
        if let scrollView = rootView as? UIScrollView {
            scrollViews.append(scrollView)
        }
        for subview in rootView.subviews {
            scrollViews.append(contentsOf: findScrollViews(in: subview))
        }
        return scrollViews
    }

    @objc private func handleTrackedScrollPan(_ gestureRecognizer: UIPanGestureRecognizer) {
        guard
            gestureRecognizer.state == .changed,
            let scrollView = gestureRecognizer.view as? UIScrollView
        else { return }

        // Center tab owns its own pill-hidden rule (auto-hide + bottom-edge
        // swipe-up to reveal). Skip the scroll-driven toggle there so a
        // nested scroll view doesn't fight the auto-hide behavior.
        guard currentIndex != MainTabBarController.centerTabIndex else { return }

        let translation = gestureRecognizer.translation(in: scrollView)
        guard abs(translation.y) > abs(translation.x) else { return }

        let topOffset = -scrollView.adjustedContentInset.top
        let nearTop = scrollView.contentOffset.y <= topOffset + 20

        if nearTop || translation.y > 6 {
            setTabBarVisible(true, animated: true)
        } else if translation.y < -6 {
            setTabBarVisible(false, animated: true)
        }
    }
}
